//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Product
    {
        public int PurchaseID { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.Guid> BundleID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
